# Use a base image with JDK 17
FROM maven:3.9.8-eclipse-temurin-17-alpine

# Set the working directory
WORKDIR /app

# Copy the Maven project files to the container
COPY pom.xml .
COPY src ./src

# Install dependencies and compile the project
RUN mvn clean compile

# Entry point for the container
CMD ["mvn", "spring-boot:run"]
